server:
  port: 8085

spring:
  application:
    name: billing-service

  datasource:
    url: jdbc:mysql://localhost:3311/invoice_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: billing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
        spring.json.type.mapping: >
          paymentCompleted:com.sparepartshop.billing_service.event.PaymentCompletedEvent,
          orderCancelled:com.sparepartshop.billing_service.event.OrderCancelledEvent