server:
  port: 8083

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:mysql://localhost:3309/customer_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          customerRegistered:com.sparepartshop.customer_service.event.CustomerRegisteredEvent

security:
  jwt:
    secret: ${JWT_SECRET:dev-jwt-secret-at-least-32-bytes-long-change-me-in-prod}
    expiration-ms: 86400000
    issuer: sparepartshop