server:
  port: 8086

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3312/payment_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          paymentCompleted:com.sparepartshop.payment_service.event.PaymentCompletedEvent,
          paymentFailed:com.sparepartshop.payment_service.event.PaymentFailedEvent,
          paymentRefunded:com.sparepartshop.payment_service.event.PaymentRefundedEvent

payment:
  mock:
    success-rate: 90
    webhook-delay-ms: 3000

