server:
  port: 8086

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3312/payment_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



payment:
  mock:
    success-rate: 90
    webhook-delay-ms: 3000

